# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

name: 'FileChangeCalc'
description: 'Action to calculate file changes in pull request commits.'
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
  pullRequestId:
    description: >
      Id of the pull request submitted by the user.
    required: true
    default: ${{ github.event.number }}
  format:
    description: >
      Format of the steps output context.
      Can be 'space_delimited', 'csv', or 'json'.
    required: true
    default: json
runs:
  using: 'docker'
  image: 'Microsoft.IoT.ModelsRepository.ChangeCalc/src/Dockerfile'
  entrypoint: '/entrypoint.sh'

outputs:
  all:
    description: >
      Array of all changed files.
  added:
    description: >
      Array of added files.
  modified:
    description: >
      Array of modified files.
  removed:
    description: >
      Array of removed files.
  renamed:
    description: >
      Array of renamed files.
  added_modified:
    description: >
      Array of all added and modified files.