name: Publish GitHub

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore resolvers/dotnet

      - name: Build
        run: dotnet build --no-restore --configuration Release resolvers/dotnet

      - name: Test
        run: dotnet test --no-restore --verbosity normal resolvers/dotnet

      - name: Pack
        run: dotnet pack --verbosity normal resolvers/dotnet

      - name: Configure GitHub feed
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -n github -u ${{ github.repository_owner }} -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text

      - name: Push to Nuget
        run: |
          for f in resolvers/dotnet/**/*.nupkg
          do
              dotnet nuget push $f --source github --skip-duplicate
          done
        shell: bash
