name: Push

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore resolvers/dotnet

      - name: Build
        run: dotnet build --no-restore --configuration Release resolvers/dotnet

      - name: Test
        run: dotnet test --no-restore --verbosity normal resolvers/dotnet

      - name: Pack
        run: dotnet pack --verbosity normal resolvers/dotnet
        
      - name: Configure ADO feed
        run: dotnet nuget add source https://pkgs.dev.azure.com/azure-iot-pnp/_packaging/azure.iot.pnp.libraries/nuget/v3/index.json -n PnPFeed -u dmr_pkgs -p ${{ secrets.ADO_PKGS_PAT_TOKEN }} --store-password-in-clear-text

      - name: push
        run: |
          for f in resolvers/dotnet/**/*.nupkg
          do
              dotnet nuget push $f --source PnPFeed
          done
        shell: bash